server:
  port: 8080

logging:
  level:
    root: DEBUG
    org.springframework.web: TRACE
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.gateway: TRACE
#    org.springframework.boot.autoconfigure: DEBUG


spring:
  autoconfigure:
    # TODO: remove when fixed https://github.com/spring-projects/spring-security/issues/6314
    exclude: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  thymeleaf:
    cache: false
#  security:
#    oauth2:
#      client:
#        registration:
#          login-client:
#            provider: uaa
#            client-id: acme
#            client-secret: acmesecret
#            authorization-grant-type: authorization_code
#            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope: user
#        provider:
#          uaa:
#            authorization-uri: http://10.104.204.130:9191/uaa/oauth/authorize
#            token-uri: http://10.104.204.130:9191/uaa/oauth/token
#            user-info-uri: http://10.104.204.130:9191/uaa/user
#            user-name-attribute: name
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#          lower-case-service-id: true
#          filters:
#            - name: RewritePath
#              args:
#                regexp: "'/' + serviceId + '/(?<remaining>.*)'"
#                replacement: "'/${remaining}'"
#            - name: TokenRelay
#          url-expression: "'http://'+serviceId"
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway