server:
  port: 8080
  error:
    include-stacktrace: always
    include-exception: true
    whitelabel:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.gateway: INFO
#    org.springframework.boot.autoconfigure: DEBUG


spring:
  autoconfigure:
    # TODO: remove when fixed https://github.com/spring-projects/spring-security/issues/6314
    exclude: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: uaa
            client-id: acme
            client-secret: acmesecret
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: user
        provider:
          uaa:
            authorization-uri: http://10.104.204.130:9191/uaa/oauth/authorize
            token-uri: http://10.104.204.130:9191/uaa/oauth/token
            user-info-uri: http://10.104.204.130:9191/uaa/user
            user-name-attribute: name
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          filters:
            - name: RewritePath
              args:
                regexp: "'/' + serviceId + '/(?<remaining>.*)'"
                replacement: "'/${remaining}'"
            - name: TokenRelay
#          url-expression: "'http://'+serviceId + ':' + port"
          url-expression: "'http://' + host + ':' + port"
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway
